apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lip-registry-data
  namespace: lip-registry
  labels:
    app: lip-registry
    app.kubernetes.io/part-of: lip-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
