[package]
name = "li-crypto"
version = "0.1.0"
edition = "2026"
license = "Apache-2.0 OR MIT"
description = "ChaCha20-Poly1305, X25519, TLS record crypto (Li-first)"

[dependencies]
# path = { path = "../other" }   # lip 8b+
# registry = "1.0.0"             # lip 8d+

[package.metadata.li]
github_repo = "li-crypto"
import_name = "crypto"
min_lic = "0.1.0"
maintainer = "li-langverse"
pkg_id = "PKG-li-crypto"

[package.repository]
url = "https://github.com/li-langverse/li-crypto"
documentation = "https://li-langverse.github.io/li-language/ecosystem/li-crypto/"
changelog = "https://github.com/li-langverse/li-crypto/blob/main/CHANGELOG.md"
