apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-backup-storage
  namespace: gitlab
  labels:
    app: gitlab-backup
    app.kubernetes.io/name: gitlab-backup
    app.kubernetes.io/part-of: gitlab-ha
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 30Gi
