#!/usr/bin/env python3
"""Render a Caddy v2 site block from validated li-httpd TOML (M1 bridge until li-httpd ships)."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from httpd_config import CanonicalRoute, ConfigError, HttpdConfig, load_httpd_full, load_httpd_sites


def _caddy_path(route: CanonicalRoute) -> str:
    p = route.path
    if route.path_kind == "prefix_strip":
        return p.rstrip("/") + "/*"
    if route.path_kind == "prefix":
        return p.rstrip("/") + "/*"
    return p


def _route_block(route: CanonicalRoute, cfg: HttpdConfig) -> str:
    path = _caddy_path(route)
    if route.method != "*":
        handle_open = (
            f"@route_{route.name} {{\n"
            f"  method {route.method}\n"
            f"  path {path}\n"
            f"}}\n"
            f"handle @route_{route.name} {{\n"
        )
    else:
        handle_open = f"handle {path} {{\n"

    action = route.action
    body = ""
    if action.startswith("static:"):
        slug = action.split(":", 1)[1]
        if slug == "healthcheck":
            body = '    respond "ok" 200\n'
        else:
            body = f'    respond "{slug}" 200\n'
    elif action.startswith("proxy:"):
        uid = action.split(":", 1)[1]
        peers = cfg.upstreams[uid]
        targets = " ".join(peers)
        body = f"    reverse_proxy {targets}\n"
    else:
        raise ConfigError(f"unsupported action for caddy render: {action!r}")

    hdr = ""
    if route.headers:
        for k, v in sorted(route.headers.items()):
            hdr += f"    header_up {k} {v}\n"

    return f"{handle_open}{hdr}{body}}}\n"


def render_caddyfile(configs: list[HttpdConfig]) -> str:
    return "\n".join(render_caddy(cfg).rstrip() for cfg in configs) + "\n"


def render_caddy(cfg: HttpdConfig) -> str:
    hosts = [h.strip() for h in cfg.host.split(",") if h.strip()]
    site_hosts = ", ".join(hosts)
    lines = [
        "# Generated by lis http render-caddy — do not edit by hand",
        f"# Source profile: li-httpd TOML (host={cfg.host})",
        "",
    ]
    tls_line = ""
    if cfg.tls in (None, "", "off", "false"):
        tls_line = ""
    elif cfg.tls in ("lets_encrypt", "acme", "auto"):
        tls_line = ""
    else:
        tls_line = f"    tls {cfg.tls}\n"

    body_limit = ""
    if cfg.max_body:
        body_limit = f"    request_body {{ max_size {cfg.max_body} }}\n"

    site = [f"{site_hosts} {{"]
    if tls_line:
        site.append(tls_line.rstrip())
    if body_limit:
        site.append(body_limit.rstrip())

    for route in sorted(cfg.routes, key=lambda r: r.priority):
        site.append(_route_block(route, cfg).rstrip())

    site.append("}")
    lines.extend(site)
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Render Caddyfile from li-httpd TOML")
    ap.add_argument("config", type=Path)
    ap.add_argument("-o", "--output", type=Path, help="write Caddyfile (default: stdout)")
    args = ap.parse_args()
    try:
        sites = load_httpd_sites(args.config)
        text = render_caddyfile(sites)
    except ConfigError as e:
        print(f"config error: {e}", file=sys.stderr)
        return 1
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8")
        print(f"wrote {args.output}")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
